package main

import (
	"context"
	"fmt"
	"net/http"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"
)

type prometheusGauge struct {
	value float64
}

// PrometheusSink serves a Prometheus text exposition endpoint at /metrics.
// Each Send() updates the current gauge value for the (metric, device) pair;
// the latest state is returned on every scrape. No renderer is used —
// the sink writes Prometheus text format directly.
type PrometheusSink struct {
	metricName string
	mu         sync.RWMutex
	gauges     map[string]map[string]prometheusGauge // metric → device → gauge
	server     *http.Server
}

func NewPrometheusSink(port int, metricName string) (*PrometheusSink, error) {
	if metricName == "" {
		metricName = "genx"
	}

	s := &PrometheusSink{
		metricName: metricName,
		gauges:     make(map[string]map[string]prometheusGauge),
	}

	mux := http.NewServeMux()
	mux.HandleFunc("/metrics", s.handleMetrics)

	srv, err := startHTTPServer(port, mux)
	if err != nil {
		return nil, fmt.Errorf("prometheus: %w", err)
	}
	s.server = srv

	return s, nil
}

func (s *PrometheusSink) Send(dp DataPoint) error {
	s.mu.Lock()
	defer s.mu.Unlock()

	set := func(name, device string, val float64) {
		if s.gauges[name] == nil {
			s.gauges[name] = make(map[string]prometheusGauge)
		}
		s.gauges[name][device] = prometheusGauge{value: val}
	}

	if len(dp.Fields) > 0 {
		for field, val := range dp.Fields {
			set(s.metricName+"_"+promSanitizeName(field), dp.Device, val)
		}
	} else if dp.Value != nil {
		set(s.metricName, dp.Device, *dp.Value)
	}
	return nil
}

func (s *PrometheusSink) handleMetrics(w http.ResponseWriter, _ *http.Request) {
	s.mu.RLock()
	defer s.mu.RUnlock()

	names := make([]string, 0, len(s.gauges))
	for name := range s.gauges {
		names = append(names, name)
	}
	sort.Strings(names)

	w.Header().Set("Content-Type", "text/plain; version=0.0.4; charset=utf-8")

	for _, name := range names {
		devices := s.gauges[name]
		devList := make([]string, 0, len(devices))
		for d := range devices {
			devList = append(devList, d)
		}
		sort.Strings(devList)

		fmt.Fprintf(w, "# HELP %s IoT sensor reading generated by genx\n", name)
		fmt.Fprintf(w, "# TYPE %s gauge\n", name)
		for _, dev := range devList {
			g := devices[dev]
			fmt.Fprintf(w, "%s{device=%s} %s\n",
				name,
				promQuoteLabelValue(dev),
				strconv.FormatFloat(g.value, 'f', -1, 64),
			)
		}
	}
}

func (s *PrometheusSink) Close() error {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	return s.server.Shutdown(ctx)
}

// promSanitizeName converts a field name to a valid Prometheus metric name suffix
// by replacing any character that is not [a-zA-Z0-9_] with an underscore.
func promSanitizeName(s string) string {
	var b strings.Builder
	for _, r := range s {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' {
			b.WriteRune(r)
		} else {
			b.WriteByte('_')
		}
	}
	return b.String()
}

// promQuoteLabelValue returns a properly quoted and escaped Prometheus label value.
func promQuoteLabelValue(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, "\n", `\n`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	return `"` + s + `"`
}
